baseURL = 'https://example.org/'
locale = 'es-es'
title = 'Tu Cultivo en Casa'


[params]
mainSections = ["guias-cultivo", "huerto-urbano", "cuidado-mantenimiento", "reviews-productos"]

[taxonomies]
category = "categoria"
tag = "tag"
